// Plays a title, then clicks the seek bar at 70% and checks playback continues there.  node tools/seektest.mjs "#/watch/movie/tt1392214"
import puppeteer from 'puppeteer-core';
import { readFileSync } from 'node:fs';
const hash = process.argv[2];
const KEY = readFileSync(new URL('./.rdkey', import.meta.url), 'utf8').trim();
const b = await puppeteer.launch({ executablePath: 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', headless: true, args: ['--autoplay-policy=no-user-gesture-required', '--mute-audio'] });
const p = await b.newPage(); await p.setViewport({ width: 1440, height: 900 });
await p.goto('http://localhost:5173/#/welcome');
await p.evaluate(async K => { const s = await import('/js/core/store.js'); if (!s.profiles.get().length) s.profiles.set([{ id: 't', name: 'T', avatar: 'cat', theme: 'ink', ink: '#f00' }]); s.activeProfileId.set(s.profiles.get()[0].id); s.progress.set({}); await s.saveRdKey(K); }, KEY);
await p.goto('http://localhost:5173/' + hash);
const state = () => p.evaluate(() => { const v = document.querySelector('video'); const tt = document.querySelector('.pl-seek'); return { ct: v && +v.currentTime.toFixed(1), rs: v && v.readyState, shown: tt && tt.getAttribute('aria-valuetext') }; });
const until = async (f, ms) => { const t0 = Date.now(); while (Date.now() - t0 < ms) { const s = await state(); if (f(s)) return s; await new Promise(r => setTimeout(r, 1000)); } return state(); };
console.log('start', await until(s => s.ct > 3, 120000));
await p.mouse.move(700, 450);
const bar = await p.$('.pl-seek'); const r = await bar.boundingBox();
await p.mouse.click(r.x + r.width * .7, r.y + r.height / 2);
console.log('clicked 70%', await state());
await new Promise(r => setTimeout(r, 3000));
const s1 = await state();
console.log('after 3s', s1);
console.log('after wait', await until(s => s.rs >= 3 && s.ct > 3, 90000));
await b.close();
